# Generated by Django 4.2.4 on 2023-08-08 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1000000000000000), django.core.validators.MaxLengthValidator(9999999999999999)]),
        ),
    ]
