# Generated by Django 4.2.4 on 2023-08-08 05:10

import accounts_Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Api', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(unique=True, validators=[accounts_Api.models.validate_account_number]),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
