# Generated by Django 4.2.4 on 2023-08-08 05:16

import accounts_Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Api', '0003_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=19, unique=True, validators=[accounts_Api.models.validate_account_number]),
        ),
    ]
